export const AUTH = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  BADGE_LOGIN: 'BADGE_LOGIN',
  PROFILE_STATUS: 'PROFILE_STATUS',
};

export const BADGES = {
  FETCH: 'FETCH',
  ADD: 'ADD',
  FIRST_LOAD: 'FIRST_LOAD',
};
