# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ release ]


jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:livestream
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./client
