name: Firebase Deploy

on:
    push:
        branches:
            - release

jobs:
    firebase-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: '10.x'
            - run: cd ./client
            - run: cd client && npm ci
            - run: cd client && npm run build
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting:livestream
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  PROJECT_PATH: ./client
